### ISSUE TITLE
Possible to package for OPM?

### ISSUE THREAD

**Issue by nelson2005** [jprjr/lua-resty-exec#1]
This is a neat project... could I talk you into packaging this and netstrings for OPM?

https://opm.openresty.org/

**Comment by jprjr** [comment]
I'll give it a try! Had a hangup with opm and netstring - opm seems to be picky about the project name and repository name matching exactly, but mine don't. https://github.com/openresty/opm/issues/47

**Comment by jprjr** [comment]
Done and done! This is now listed on OPM

**Comment by nelson2005** [comment]
Thanks for a neat little package!
