### ISSUE TITLE
sh: resty: command not found

### ISSUE THREAD

**Issue by aogooc** [jprjr/lua-resty-exec#10]
Although it can determine what is the problem, but this is not very friendly.

```
aogooc-dev-2:openresty aogooc$ sudo bin/opm get jprjr/lua-resty-exec
* Fetching jprjr/lua-resty-exec  
  Downloading https://opm.openresty.org/api/pkg/tarball/jprjr/lua-resty-exec-1.2.0.opm.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4875  100  4875    0     0  33857      0 --:--:-- --:--:-- --:--:-- 33854
sh: resty: command not found
ERROR: luajit is required but is not available according to resty: 
```

**Comment by jprjr** [comment]
Are you able to install other modules with opm, or is it just lua-resty-exec that's giving you a problem?

**Comment by aogooc** [comment]
Only  lua-resty-exec , install other modules normally, use mac os building.

**Comment by jprjr** [comment]
Are you sure you have your `$PATH` set correctly? I just installed OpenResty on Mac OS via homebrew, and `opm get jprjr/lua-resty-exec` ran fine.

What happens if you run `which resty` and/or `sudo bash -c 'which resty'` from that directory?

**Comment by aogooc** [comment]
I know this problem, set the environment variable to work. 

after testing, some installation packages use opm to install this problem, this should be related to opm's operating mechanism.

Thank you for your trouble.
