### ISSUE TITLE
openresty - Permission denied connecting to sockexec

### ISSUE THREAD

**Issue by dtanner** [jprjr/lua-resty-exec#12]
Hi, I'm trying it out for the first time in an openresty docker installation.  I'm not sure if I simply have a permissions setup problem, or am doing something else wrong in my config.

I successfully tested sockexec in my container by manually running sockexec, then running one of the perl example scripts in the container.  Now when trying to execute a command in a lua script in openresty, I'm getting this permission error:  

    connect() to unix:/tmp/exec.sock failed (13: Permission denied)

Here's how I'm starting sockexec and openresty.  This is from a sh script referenced in my Dockerfile ENTRYPOINT:
```
/opt/sockexec/bin/sockexec /tmp/exec.sock &
/usr/local/openresty/bin/openresty -p / -g "daemon off;" -c /nginx.conf
```

This is how I'm trying to test calling a command in the lua script:
```
     local exec = require'resty.exec'
     local prog = exec.new('/tmp/exec.sock')
     local res, err = prog("uname")
```

Here's the process information when running in the docker container - they're both initiated as root:
```
root        11  0.0  0.2  50956  6916 ?        S    15:44   0:00 nginx: master process /usr/local/openresty/bin/openresty -p / -g daemon off; -c /nginx.conf
root         8  0.0  0.0    252     4 ?        S    16:47   0:00 /opt/sockexec/bin/sockexec /tmp/exec.sock
```

Any tips on what I'm doing wrong?  Maybe just missing a setup step?  Thanks a ton for any help.

**Comment by jprjr** [comment]
What user is the nginx worker process running as? Do you have anything in your nginx.conf that changes the user?

**Comment by dtanner** [comment]
Ah - i'm not very experienced with nginx - that was it.  I mistakenly assumed that nginx would run as the user that started the process, but that's not the case.  I configured nginx to run as the intended user, and that fixed the issue.  Thanks again for your help!

**Comment by jprjr** [comment]
No problem! Always happy to help :)

**Comment by 7dir** [comment]
Should add to readme

```sh
sockexec /tmp/exec.sock
chown www-data:www-data /tmp/exec.sock
```
