### ISSUE TITLE
Receive data chunk handler?

### ISSUE THREAD

**Issue by dlannan-fmad** [jprjr/lua-resty-exec#19]
I have been looking at the code, and I was wondering how hard would it be to have a data chunk handler on the stdout from the running process. 

I think I could modify the grab_ns method in the socket.lua but Im not sure what sort of impact this would have on other functionality. Any thoughts or tips? Is this project still active?

**Comment by jprjr** [comment]
Not sure I follow - you can pass a `stdout` function that will be called on each chunk of output, this is straight out of the `README`

```
local exec = require'resty.exec'
local prog = exec.new('/tmp/exec.sock')
local res, err = prog( {
    argv = 'cat',
    stdin = 'example',
    stdout = function(data) print(data) end,
    stderr = function(data) print("error:", data) end
} )
```

Re: this project being active, not really. I have a few internal applications that still use it, but for newer applications I've been using [`ngx.pipe`](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/pipe.md) since that's built-in to OpenResty.

For other, non-openresty applications, I rarely need to spawn other programs. If I do, I just use `os.execute`

**Comment by dlannan** [comment]
As far as I can tell in the socket code, it does a fetch on the socket until all the stdout is read. So, if you had say a large file your were reading or similar, the stdout handler wont get called until the socket reading (recieve()) is complete? Or thats how I interpret it. Maybe missing something obvious.

I havent used pipe. Will have a look if it is a similar capability. Thanks for the response. I appreciate the quick feedback.

**Comment by jprjr** [comment]
If you had a large file, large chunk of data, etc - it will get called in chunks.

The underlying `sockexec` daemon splits the output into chunks, and sends them out as [netstrings](https://en.wikipedia.org/wiki/Netstring) - I'd have to go through the `sockexec` code again, but if I recall correctly the default size is 4096 or 8192 bytes, something like that.

The `grab_ns` function is decoding an incoming netstring, it's first reading in the size of the netstring, then the actual contents. The `sockexec` daemon is sending pairs like,

```
6:stdout,11:hello world,
```

Which corresponds to receiving the data `hello world` on `stdout`. Then the `grab_ns` function calls the appropriate callback.

**Comment by dlannan** [comment]
Yes, thats how I understand it too. However in the receive() method there is a while loop that continues grab_ns until all data is read: https://github.com/jprjr/lua-resty-exec/blob/6fd94484432d65e666f1002a552f7d0fd4313fd6/lib/resty/exec/socket.lua#L303
I think this means, if you send it a large file (or data output via stdout), then it will try to insert pairs until all stdout data is consumed - this is what Im seeing at the moment, and the handler gets called after with a big data buffer (if its too big there are other issues too). 
I suspect this module isnt really suited to that type of use case.

**Comment by jprjr** [comment]
Oh crud, yeah - that's a bug, and definitely not what I intended. The intent was to have the handler be called with each chunk. Or at least I think it was, I haven't looked at this module that deeply in a few years. But I'm pretty certain I wanted the stdout callback to be called on each chunk.

If you're using OpenResty, `ngx.pipe` is definitely the way to go, it has all the features this module has, and more.

**Comment by dlannan-fmad** [comment]
Oh. cool. I have been playing with pipe. It looks very similar and has some nice features. Thanks for the help and tips. really appreciate the time.
