### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by jurafa** [jprjr/lua-resty-exec#3]
Could you add some installation notes for OpenResty to README.md?

**Comment by jprjr** [comment]
Can do - what kind of instructions are you looking for? Setting up sockexec?

**Comment by jurafa** [comment]
Setting up sockexec should be in the repository for sockexec and I believe that it is there and is completely fine.
I just think that for beginners in OpenResty it would be nice to find here that it can be installed using openresty package manager (opm).

**Comment by jprjr** [comment]
Done and done! I updated the readme with instructions for LuaRocks and OpenResty
