### ISSUE TITLE
Not thread safe

### ISSUE THREAD

**Issue by jurafa** [jprjr/lua-resty-exec#4]
Hi.
I am trying to execute multiple shell commands separately in different nginx threads. 

I have a single script that executes shell command:
```
function ramUsage.service(...)
    local prog = exec.new('/tmp/exec.sock')
    prog.argv = {'cat', '/proc/meminfo'}
    local res, err = prog()
    if err ~= nil then
        ngx.say(err)
    end

    ngx.say(res.stdout)
end
```

Then I have another script that spawns 3 threads and waits for the result. 
```
local ramUsageService = require 'ramUsage'

local threads = {}

for i = 1, 3 do
    local thread = ngx.thread.spawn(ramUsageService.service)
    table.insert(threads, thread)
end

local responses = {}

for i = 1, #threads do
    local ok, res = ngx.thread.wait(threads[i])
    if ok then
        if res ~= nil then
            table.insert(responses, res)
        end
    else
        ngx.say('thread error')
    end
end


ngx.say('test finished!')
```

The result usually is that some threads time-out without getting any data. I guess that it is because the resources do not get disposed. What is recommended the approach. Should I be using some locking mechanism?

 Thanks

**Comment by jprjr** [comment]
It turns out the sockexec binary had a few race-condition type bugs, try downloading the latest release (1.0.6) and see if that fixes the problem. https://github.com/jprjr/sockexec/releases/tag/1.0.6

**Comment by jurafa** [comment]
I have tried the case that I described in the first comment and it seems to work very well. Thanks.
